### ISSUE TITLE
undefined reference to `cpr::Session::~Session()'

### ISSUE THREAD

**Issue by Stuip** [snme/cs106L-assignment1#3]
Hi, thank you for sharing the resourses of CS106L! I am not Stanford student and i'm confused about the environment.

#### Version and Platform
ubuntu 20.04.1
cmake 3.22.2
gcc 7.5.0

i got this issue when i executed the shell ./setup.sh

/usr/bin/ld: ../wikiscraper.cpp.o: in function `cpr::Response cpr::Get<cpr::Url>(cpr::Url&&)':
wikiscraper.cpp:(.text._ZN3cpr3GetIJNS_3UrlEEEENS_8ResponseEDpOT_[_ZN3cpr3GetIJNS_3UrlEEEENS_8ResponseEDpOT_]+0x6a): undefined reference to `cpr::Session::~Session()'
/usr/bin/ld: wikiscraper.cpp:(.text._ZN3cpr3GetIJNS_3UrlEEEENS_8ResponseEDpOT_[_ZN3cpr3GetIJNS_3UrlEEEENS_8ResponseEDpOT_]+0x8f): undefined reference to `cpr::Session::~Session()'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/main.dir/build.make:120：main] error 1
make[1]: *** [CMakeFiles/Makefile2:83：CMakeFiles/main.dir/all] error 2
make: *** [Makefile:91：all] error 2

**Comment by zjx-pku** [comment]
I also have the same error in assignment 1, while the "./setup.sh" and "./build_and_run.sh" in assignment 2 can run without any errors.

My Platform and version are:

- Linux version 5.10.16.3-microsoft-standard-WSL2
- cmake version 3.22.2
- gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0

**Comment by coding-famer** [comment]
Hi  I have the same problem too! I guess we use the wrong cpr virsion? But I have no idea to fix it

**Comment by ghost** [comment]
I also have the same error in assignment 1

My Platform and version are:
* WSL2 - ubuntu 20.04.4
* cmake version 3.16.3
* gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0

**Comment by Crabtux** [comment]
I also had the same error in assignment 1.

My platform and version are:

- Ubuntu 20.04
- CMake version 3.16.3
- gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.1)

However, I managed to fix the error simply by adding a cpp file, which uses the cpr library, into the project. I guess by doing this, I forced to statically link to the cpr library. It may be somewhat ugly, but it did fix the problem.

I have forked the repository and created a commit, maybe you can have a try?
link: [https://github.com/Crabtux/cs106L-assignment1](https://github.com/Crabtux/cs106L-assignment1)

**Update: Oh no, even though I managed to get it run, when I try to call the `findWikiLadder` function, it will throw a 'std:bad_alloc' exception and then crash. I guess there is something wrong with the `wikiscraper.cpp.o` file. Maybe I should wait for the author to fix this problem or directly jump to the second assignment**😂

**Comment by Stuip** [comment]
> 

It done, Thanks! Bro

**Comment by pUmpKin-Co** [comment]
I have the same error. Any suggestion for fixing this problem?

**Comment by CandyOre** [comment]
Same error here, waiting for suggestions :(

**Comment by Shengqi-Pan** [comment]
Same error again!
